version: '3'
services:

  consul:
    image: consul
    ports:
      - 8500:8500
    expose:
      - 8500
    command: |
      sh -c 'set -uex; \
        consul agent -server -bootstrap-expect=1 -data-dir /consul/data -node=agent-one -enable-script-checks=true -ui -disable-host-node-id -client 0.0.0.0 & \
        sleep 20 && \
        consul kv put -http-addr=http://localhost:8500 config/init true &&\
        consul kv put config/Gateway/security.user.name admin &&\
        consul kv put config/Gateway/security.user.password admin &&\
        consul kv put config/Authorization/application.jwt.secretKey securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure &&\
        consul kv put config/Authorization/application.jwt.tokenExpirationAfterDays 10 &&\
        consul kv put config/Authorization/security.user.name admin &&\
        consul kv put config/Authorization/security.user.password admin &&\
        consul kv put config/Authorization/mxpipeline.ldap.url ldap://root-dc.murex.com:3268 &&\
        consul kv put config/Authorization/mxpipeline.ldap.domain murex.com &&\
        consul kv put config/Authorization/spring.datasource.platform postgres &&\
        consul kv put config/Authorization/spring.datasource.url jdbc:postgresql://mxem_postgres_1:5432/mxem &&\
        consul kv put config/Authorization/spring.datasource.username postgres &&\
        consul kv put config/Authorization/spring.datasource.password Staring123 &&\

        consul kv put config/Authorization/spring.datasource.driverClassName=org.postgresql.Driver &&\
        consul kv put config/Authorization/spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect &&\
        consul kv put config/Authorization/spring.jpa.show-sql=false &&\
        consul kv put config/Authorization/spring.jpa.hibernate.ddl-auto=create &&\

        consul kv put config/Environments/spring.data.mongodb.port 27017 &&\
        consul kv put config/Environments/spring.data.mongodb.host mxem_mongo_1 &&\
        consul kv put config/Environments/spring.data.mongodb.database environments &&\
        consul kv put config/Environments/application.jwt.secretKey securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure &&\
        consul kv put config/Environments/application.jwt.tokenExpirationAfterDays 10 &&\
        consul kv put config/Environments/security.user.name admin &&\
        consul kv put config/Environments/security.user.password admin &&\
        consul kv put config/Environments/spring.rabbitmq.host mxem_rabbitmq_1 &&\
        consul kv put config/Environments/spring.rabbitmq.port 5672 &&\
        consul kv put config/Environments/spring.rabbitmq.username guest &&\
        consul kv put config/Environments/spring.rabbitmq.password guest &&\
        consul kv put config/Environments/javainuse.rabbitmq.exchange javainuse.exchange &&\
        consul kv put config/Environments/javainuse.rabbitmq.queue javainuse.queue &&\
        consul kv put config/Environments/javainuse.rabbitmq.routingkey javainuse.routingkey &&\

        consul kv put config/Scheduler/security.user.name admin &&\
        consul kv put config/Scheduler/security.user.password admin &&\
        consul kv put config/Scheduler/spring.rabbitmq.host mxem_rabbitmq_1 &&\
        consul kv put config/Scheduler/spring.rabbitmq.port 5672 &&\
        consul kv put config/Scheduler/spring.rabbitmq.username guest &&\
        consul kv put config/Scheduler/spring.rabbitmq.password guest &&\
        consul kv put config/Scheduler/javainuse.rabbitmq.exchange javainuse.exchange &&\
        consul kv put config/Scheduler/javainuse.rabbitmq.queue javainuse.queue &&\
        consul kv put config/Scheduler/javainuse.rabbitmq.routingkey javainuse.routingkey &&\
        consul kv put config/Scheduler/spring.data.mongodb.port 27017 &&\
        consul kv put config/Scheduler/spring.data.mongodb.host mxem_mongo_1 &&\
        consul kv put config/Scheduler/spring.data.mongodb.database scheduler &&\
        consul kv put config/Scheduler/application.jwt.secretKey securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure &&\
        consul kv put config/Scheduler/application.jwt.tokenExpirationAfterDays 10 &&\
        tail -f /dev/null'

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      # - POSTGRES_DB=mxem
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgresvolume:/var/lib/postgresql/data

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"
    # environment:
      # - MONGO_INITDB_DATABASE=environments
      # - MONGO_INITDB_DATABASE=scheduler
    volumes:
      - mongovolume:/data/db

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    expose:
      - "5672"

  webapp: 
    build:
      context: ../website
      dockerfile: Dockerfile
    image: angularservice:1
    volumes: 
      - angularvolume:/usr/src/app
    ports: 
      - '4200:4200' 
    command: > 
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    depends_on:
      - authorization
      - gateway
      - environments
      - scheduler

  gateway:
    build:
      context: ./Gateway 
      dockerfile: Dockerfile
    image: gateservice:1
    ports:
      - 8081:8081
    expose:
      - 8081
    depends_on:
      - consul
 
  authorization:
    build:
         context: ./Authorization
         dockerfile: Dockerfile
    image: authservice:1
    depends_on:
      - consul
      - postgres
    
 
  environments:
    build:
         context: ./Environments
         dockerfile: Dockerfile
    image: envservice:1
    depends_on:
      - consul
      - mongo
      - rabbitmq

  scheduler:
    build:
         context: ./Scheduler
         dockerfile: Dockerfile
    image: schedservice:1
    depends_on:
      - consul
      - mongo
      - rabbitmq 
 
volumes:
  consulvolume:
  mongovolume:
  postgresvolume:
  rabbitmqvolume:

  angularvolume:
  authorization_volume:
  gateway_volume:
  environments_volume:
  scheduler_volume: